3G_4/src/java/crud/PedidoController.java
package crud;

import crud.util.JsfUtil;
import crud.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("pedidoController")
@SessionScoped
public class PedidoController implements Serializable {

    private Pedido current;
    private DataModel items = null;
    @EJB
    private crud.PedidoFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PedidoController() {
    }

    public Pedido getSelected() {
        if (current == null) {
            current = new Pedido();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PedidoFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Pedido) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Pedido();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PedidoCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Pedido) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PedidoUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Pedido) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PedidoDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Pedido getPedido(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Pedido.class)
    public static class PedidoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PedidoController controller = (PedidoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "pedidoController");
            return controller.getPedido(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Pedido) {
                Pedido o = (Pedido) object;
                return getStringKey(o.getIdpedido());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Pedido.class.getName());
            }
        }

    }

}

3G_4/web/pedido/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatePedidoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePedidoLabel_idpedido}" for="idpedido" />
                    <h:inputText id="idpedido" value="#{pedidoController.selected.idpedido}" title="#{bundle.CreatePedidoTitle_idpedido}" required="true" requiredMessage="#{bundle.CreatePedidoRequiredMessage_idpedido}"/>
                    <h:outputLabel value="#{bundle.CreatePedidoLabel_idclientes}" for="idclientes" />
                    <h:inputText id="idclientes" value="#{pedidoController.selected.idclientes}" title="#{bundle.CreatePedidoTitle_idclientes}" required="true" requiredMessage="#{bundle.CreatePedidoRequiredMessage_idclientes}"/>
                    <h:outputLabel value="#{bundle.CreatePedidoLabel_nombrep}" for="nombrep" />
                    <h:inputText id="nombrep" value="#{pedidoController.selected.nombrep}" title="#{bundle.CreatePedidoTitle_nombrep}" required="true" requiredMessage="#{bundle.CreatePedidoRequiredMessage_nombrep}"/>
                    <h:outputLabel value="#{bundle.CreatePedidoLabel_descripcionp}" for="descripcionp" />
                    <h:inputTextarea rows="4" cols="30" id="descripcionp" value="#{pedidoController.selected.descripcionp}" title="#{bundle.CreatePedidoTitle_descripcionp}" required="true" requiredMessage="#{bundle.CreatePedidoRequiredMessage_descripcionp}"/>
                    <h:outputLabel value="#{bundle.CreatePedidoLabel_fechapedido}" for="fechapedido" />
                    <h:inputText id="fechapedido" value="#{pedidoController.selected.fechapedido}" title="#{bundle.CreatePedidoTitle_fechapedido}" required="true" requiredMessage="#{bundle.CreatePedidoRequiredMessage_fechapedido}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreatePedidoLabel_entregado}" for="entregado" />
                    <h:inputText id="entregado" value="#{pedidoController.selected.entregado}" title="#{bundle.CreatePedidoTitle_entregado}" required="true" requiredMessage="#{bundle.CreatePedidoRequiredMessage_entregado}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pedidoController.create}" value="#{bundle.CreatePedidoSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{pedidoController.prepareList}" value="#{bundle.CreatePedidoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreatePedidoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

3G_4/web/pedido/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPedidoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPedidoLabel_idpedido}" for="idpedido" />
                    <h:inputText id="idpedido" value="#{pedidoController.selected.idpedido}" title="#{bundle.EditPedidoTitle_idpedido}" required="true" requiredMessage="#{bundle.EditPedidoRequiredMessage_idpedido}"/>
                    <h:outputLabel value="#{bundle.EditPedidoLabel_idclientes}" for="idclientes" />
                    <h:inputText id="idclientes" value="#{pedidoController.selected.idclientes}" title="#{bundle.EditPedidoTitle_idclientes}" required="true" requiredMessage="#{bundle.EditPedidoRequiredMessage_idclientes}"/>
                    <h:outputLabel value="#{bundle.EditPedidoLabel_nombrep}" for="nombrep" />
                    <h:inputText id="nombrep" value="#{pedidoController.selected.nombrep}" title="#{bundle.EditPedidoTitle_nombrep}" required="true" requiredMessage="#{bundle.EditPedidoRequiredMessage_nombrep}"/>
                    <h:outputLabel value="#{bundle.EditPedidoLabel_descripcionp}" for="descripcionp" />
                    <h:inputTextarea rows="4" cols="30" id="descripcionp" value="#{pedidoController.selected.descripcionp}" title="#{bundle.EditPedidoTitle_descripcionp}" required="true" requiredMessage="#{bundle.EditPedidoRequiredMessage_descripcionp}"/>
                    <h:outputLabel value="#{bundle.EditPedidoLabel_fechapedido}" for="fechapedido" />
                    <h:inputText id="fechapedido" value="#{pedidoController.selected.fechapedido}" title="#{bundle.EditPedidoTitle_fechapedido}" required="true" requiredMessage="#{bundle.EditPedidoRequiredMessage_fechapedido}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditPedidoLabel_entregado}" for="entregado" />
                    <h:inputText id="entregado" value="#{pedidoController.selected.entregado}" title="#{bundle.EditPedidoTitle_entregado}" required="true" requiredMessage="#{bundle.EditPedidoRequiredMessage_entregado}"/>
                </h:panelGrid>
                <h:commandLink action="#{pedidoController.update}" value="#{bundle.EditPedidoSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditPedidoViewLink}"/>
                <br />
                <h:commandLink action="#{pedidoController.prepareList}" value="#{bundle.EditPedidoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditPedidoIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

3G_4/web/pedido/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListPedidoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPedidoEmpty}" rendered="#{pedidoController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{pedidoController.items.rowCount > 0}">
                    <h:outputText value="#{pedidoController.pagination.pageFirstItem + 1}..#{pedidoController.pagination.pageLastItem + 1}/#{pedidoController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{pedidoController.previous}" value="#{bundle.Previous} #{pedidoController.pagination.pageSize}" rendered="#{pedidoController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{pedidoController.next}" value="#{bundle.Next} #{pedidoController.pagination.pageSize}" rendered="#{pedidoController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{pedidoController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPedidoTitle_idpedido}"/>
                            </f:facet>
                            <h:outputText value="#{item.idpedido}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPedidoTitle_idclientes}"/>
                            </f:facet>
                            <h:outputText value="#{item.idclientes}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPedidoTitle_nombrep}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombrep}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPedidoTitle_descripcionp}"/>
                            </f:facet>
                            <h:outputText value="#{item.descripcionp}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPedidoTitle_fechapedido}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechapedido}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPedidoTitle_entregado}"/>
                            </f:facet>
                            <h:outputText value="#{item.entregado}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{pedidoController.prepareView}" value="#{bundle.ListPedidoViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pedidoController.prepareEdit}" value="#{bundle.ListPedidoEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pedidoController.destroy}" value="#{bundle.ListPedidoDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{pedidoController.prepareCreate}" value="#{bundle.ListPedidoCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListPedidoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

3G_4/web/pedido/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewPedidoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewPedidoLabel_idpedido}"/>
                    <h:outputText value="#{pedidoController.selected.idpedido}" title="#{bundle.ViewPedidoTitle_idpedido}"/>
                    <h:outputText value="#{bundle.ViewPedidoLabel_idclientes}"/>
                    <h:outputText value="#{pedidoController.selected.idclientes}" title="#{bundle.ViewPedidoTitle_idclientes}"/>
                    <h:outputText value="#{bundle.ViewPedidoLabel_nombrep}"/>
                    <h:outputText value="#{pedidoController.selected.nombrep}" title="#{bundle.ViewPedidoTitle_nombrep}"/>
                    <h:outputText value="#{bundle.ViewPedidoLabel_descripcionp}"/>
                    <h:outputText value="#{pedidoController.selected.descripcionp}" title="#{bundle.ViewPedidoTitle_descripcionp}"/>
                    <h:outputText value="#{bundle.ViewPedidoLabel_fechapedido}"/>
                    <h:outputText value="#{pedidoController.selected.fechapedido}" title="#{bundle.ViewPedidoTitle_fechapedido}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewPedidoLabel_entregado}"/>
                    <h:outputText value="#{pedidoController.selected.entregado}" title="#{bundle.ViewPedidoTitle_entregado}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pedidoController.destroyAndView}" value="#{bundle.ViewPedidoDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewPedidoEditLink}"/>
                <br />
                <h:commandLink action="#{pedidoController.prepareCreate}" value="#{bundle.ViewPedidoCreateLink}" />
                <br />
                <h:commandLink action="#{pedidoController.prepareList}" value="#{bundle.ViewPedidoShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewPedidoIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>